# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ethan Edwards
tagline:          'Ethan Edwards'
description:      'Ethan Edwards is a Unix lover how hopes to teach others!'
url:              https://blog.ethancedwards.com
baseurl:          /

author:
  name:           'Ethan Edwards'
  url:            https://twitter.com/ethancedwards

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ethancedwards8/ethancedwards8.github.io

plugins:
  - jeykll-paginate
  - jekyll-gist
  - redcarpet
